version: '2.3'

# Usage example: https://github.com/stilliard/docker-pure-ftpd/wiki/Docker-stack-with-Wordpress-&-FTP

services:
  ftpd_server:
    build:
        context: .
    container_name: pure-ftpd
    ports:
      - "$PORT:$PORT"
      - "30000-30009:30000-30009" # passive mode ports
    volumes:
      - type: bind
        source: "$FTP_DIRECTORY"
        target: /home/ftp/
      - type: bind
        source: ./pure-ftpd-passwd
        target: /etc/pure-ftpd/passwd
# uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
#      - "/folder_on_disk/ssl:/etc/ssl/private/"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: ftp
      FTP_USER_PASS: $FTP_PASS
      FTP_USER_HOME: /home/ftp
# also for ssl/tls:
#      ADDED_FLAGS: "--tls=2"
    restart: always
